Course work
NRG367GSI/archive-of-java-learning-projects pull request #14
Opened 2024-12-08 10:24 UTC by NRG367GSI

2024-12-08 18:34 UTC, AleksandrZhukovJava requested changes

2024-12-08 18:34 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/Employee.java
> +    }
поля, потом конструктор и только потом методы, только в таком порядке

2024-12-08 18:34 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/Employee.java
> +    private final String fullNameEmployee;
Можно без Employee

2024-12-08 18:34 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/Employee.java
> +    private Double salary;
Почему не примитив? разве может быть null?

2024-12-08 18:34 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/Employee.java
> +    private static int count() {
название должно быть глаголом

2024-12-08 18:34 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/Employee.java
> +        return Objects.hash(this.id, this.fullNameEmployee, this.department, this.salary);
На всякий случай уточняю что можно без this

2024-12-08 18:34 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/EmployeeBook.java
> +        this.book = new Employee[10];
Размер можно принимать в параметры конструктора, будет более масштабируемо

2024-12-08 18:34 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/EmployeeBook.java
> +    private String outBook;
не понял смысла этого поля, мы каждый раз на запросе пересчитываем это поле значит нет смысла его хранить

2024-12-08 18:34 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/EmployeeBook.java
> +                out = out.concat(this.book[i].toString() + "\n"); //out += this.book[i].toString() + "\n";
Это наплодит очень много переменных класса String в памяти. Лучше так не делать. Если кому то нужно будет сделать такую операцию лучше предоставить ему метод возвращающий весь массив, пусть конкатенирует сами.
+
Если всё таки такая операция нужна лучше String.join()

2024-12-08 18:34 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/EmployeeBook.java
> +        return false;
это можно и нужно сделать в 1 цикле, во время проверки на наличие сотруднка запомни место для вставки, тогда второй цикл будет не нужен

2024-12-08 18:34 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/EmployeeBook.java
> +        if (id >= 1 && id <= this.book.length) {
такие конструкции сложновато воспринимаются, лучше отдельный if вначале с return

2024-12-08 18:34 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/EmployeeBook.java
> +        Employee EmployeeSalaryMin = this.book[0];
переменные всегда с маленькой буквы

2024-12-08 18:34 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/EmployeeBook.java
> +            if (this.book[i] != null && this.book[i].getSalary() != 0 && this.book[i].getSalary() < EmployeeSalaryMin.getSalary()) {
если первый сотрудник будет null упадем тут с NPE

2024-12-08 18:34 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/EmployeeBook.java
> +    public String outFulNameEmployee() {
опять же, не очень вижу практическую ценности в этом методе, но для тренировки - ок. В любом случае переменную хранить в классе не нужно. Это все равно что хранить в нём максимальную зарплату

2024-12-08 18:34 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/EmployeeBook.java
> +            people.setSalary(percentageMultiplier * people.getSalary() + people.getSalary());
проверка на null

2024-12-08 18:34 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/EmployeeBook.java
> +                System.out.printf("%d %s %,.2f\n", people.getId(), people.getFullNameEmployee(), people.getSalary());
проверка на null

2024-12-08 18:34 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/EmployeeBook.java
> +                System.out.printf("%d %s %,.2f\n", people.getId(), people.getFullNameEmployee(), people.getSalary());
также

2024-12-08 18:34 UTC, AleksandrZhukovJava commented on AjavaBasics/seminars/exp/src/Main.java
> +    }
для себя ок, в пре не оставляй, если конечно не нужно посмотреть/прокомментировать

2024-12-11 08:14 UTC, AleksandrZhukovJava approved these changes

2024-12-11 08:14 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/Department.java
> +    Department(String description) {
public

2024-12-11 08:14 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/Employee.java
> +    public Double getSalary() {
примитив

2024-12-11 08:14 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/EmployeeBook.java
> +     * Возвращает сотрудника по индексу
по идентификатору* иначе путает, я вот сразу начал проверять почему просто не сделать return book[id];

2024-12-11 08:14 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/EmployeeBook.java
> +                sb.append("null").append("\n");
Ну уж раз собираем можно и покрасивее надпись чем null =)
А то это ты знаешь что такое null, другим людям эти буквы ни о чем не скажут

2024-12-11 08:14 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/EmployeeBook.java
> +            if (people.getId() == id) {
упадем с NPE если попадем на пустую ячейку

2024-12-11 08:14 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/EmployeeBook.java
> +                System.out.println(people.toString());
.toString() явно не надо вызывать, sout сам это делает

2024-12-11 08:14 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/EmployeeBook.java
> +            }
Тебе может быть интересен метод Arrays.binarySearch(), если захочешь, поизучай, он может упростить конструкцию с не большими потерями

2024-12-11 08:14 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/EmployeeBook.java
> +            if (this.book[i].getId() == id) {
упадем с NPE если упремся в пустую ячейку

2024-12-11 08:14 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/EmployeeBook.java
> +        Double sum = 0d;
почему не примитив?

2024-12-11 08:14 UTC, AleksandrZhukovJava commented on AjavaBasics/homeWork/courseWork_1/src/EmployeeBook.java
> +        double minSalary = Double.MAX_VALUE;
Лучше так не делать, такие участки в коде считаются костылями, потому что держаться только на том что зарплаты не превышают максимального double. 

Тут намного лучше присвоить минимальную зарплату как первую попавшуюся. Так - если мы найдем меньше, переприсвоим, если не найдем, значит угадали)

2024-12-11 08:56 UTC, NRG367GSI commented on AjavaBasics/homeWork/courseWork_1/src/EmployeeBook.java
> +                sb.append("null").append("\n");
sb.append(Objects.requireNonNullElse(employee, "null")).append("\n"); Вы имеете ввиду что то вроде этого? Или что то еще?

2024-12-14 06:27 UTC, merged